spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  dubbo:
    registry:
      address: 'nacos://127.0.0.1:8848'
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
    url: 'jdbc:h2:mem:test'
    schema: 'classpath:db/sql/demo_schema.sql'
    data: 'classpath:db/sql/demo_data.sql'
  h2:
    console:
      enabled: true
